### ISSUE TITLE
有些词会命中不了

### ISSUE THREAD

**Issue by wangtingshuai** [AbelZhou/PHP-TrieTree#1]
比如  "爱他妈的你好你好"   他妈的 命中不了, 敏感词是三个字的情况下,  有时候命中不了, 有时候敏感词在英文标点之后命中不了,

**Comment by AbelZhou** [comment]
我试了一下 可以命中

**Comment by abelzhou** [comment]
我试了一下可以命中，自带的字典只是一个示范，具体的字典库需要你自己去制作。

**Comment by wangtingshuai** [comment]
你试试 "胡习近平你好你好圣诞节" 我用的是demo里面14000的字典
