### ISSUE TITLE
请问想把内容里违禁的关键词替换成*号怎么操作？

### ISSUE THREAD

**Issue by sevend93** [AbelZhou/PHP-TrieTree#7]
请问想把内容里违禁的关键词替换成*号怎么操作？不太会使用组件的替换这个方法

**Comment by abelzhou** [comment]
这个仓库只负责检索出来相应的关键词，并不负责具体的替换过程。
假设你有10w+关键词都是需要替换的。A篇3000字的文章当中具有30个关键词需要替换。
那么你可以用这个库快速寻找到30个关键词，并携带出他们需要替换的内容，然后replace掉就可以了。而不需要直接用10w个关键词进行匹配，这样做效率太低了。
在这个库中每一个关键词都可以携带进去一个自定义数组，数组可以是任何内容，在黄反词领域就是*，在内链领域就是需要加的链接。甚至是内容标签，比如：肖申克救赎-＞电影    兰蔻->化妆品  波音747->飞机等，根据内容关键词的不同对内容进行分类等。
