### ISSUE TITLE
求指教，Fatal error: Uncaught Error: Class 'swoole_http_server' not found in /opt/lampp/htdocs/vendor/abelzhou/php-trie-tree/demo/swoole_server.php:13 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/vendor/abelzhou/php-trie-tree/demo/swoole_server.php on line 13

### ISSUE THREAD

**Issue by zhaojinzhou** [AbelZhou/PHP-TrieTree#8]
Fatal error: Uncaught Error: Class 'swoole_http_server' not found in /opt/lampp/htdocs/vendor/abelzhou/php-trie-tree/demo/swoole_server.php:13 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/vendor/abelzhou/php-trie-tree/demo/swoole_server.php on line 13

**Comment by abelzhou** [comment]
应该是缺少swoole扩展导致的
