### ISSUE TITLE
Hi！

### ISSUE THREAD

**Issue by huizhang001** [AbelZhou/PHP-TrieTree#9]
您好，看了您的代码感觉受益匪浅，现在想把代码稍微改造一下，当做我们开源项目的一个组件来使用，完成后会注明来源，保证不以盈利为目的，想征求一下您的同意。

**Comment by abelzhou** [comment]
可以的，改造的不错可以PR给我，毕竟很久没维护了。。额

**Comment by huizhang001** [comment]
能+个联系方式吗，有不懂的地方可以请教大佬，我发你邮件了,可以把微信或者qq发我一下，仰慕一下。哈哈

**Comment by huizhang001** [comment]
可以+个联系方式吗，方便仰慕大佬哈哈。

在 2019-10-18 20:17:31，"Abel" <notifications@github.com> 写道：


可以的，改造的不错可以PR给我，毕竟很久没维护了。。额

**Comment by AbelZhou** [comment]
[cid:F89B4169-F86E-4BAB-A9D3-86F8270B8F49]

On Oct 18, 2019, at 21:10, 会长 <notifications@github.com<mailto:notifications@github.com>> wrote:

可以+个联系方式吗，方便仰慕大佬哈哈。

在 2019-10-18 20:17:31，"Abel" <notifications@github.com<mailto:notifications@github.com>> 写道：


可以的，改造的不错可以PR给我，毕竟很久没维护了。。额
